version: "3.8"
services:
  db:
    container_name: ${POSTGIS_SERVER}
    hostname: ${POSTGIS_SERVER}
    image: postgis/postgis:13-3.1-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGIS_USER}
      POSTGRES_PASSWORD: ${POSTGIS_PASS}
      POSTGRES_DB: ${POSTGIS_DBNAME}
    ports:
      - ${POSTGIS_PORT}:5432
    volumes:
      - postgis-data:/var/lib/postgresql/data
  pgadmin:
    container_name: ${PGADMIN_SERVER}
    hostname: ${PGADMIN_SERVER}
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USERNAME}@${PGADMIN_DOMAIN}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_SERVER_JSON_FILE: /servers.json
    ports:
      - ${PGADMIN_HTTP_PORT}:80
    volumes:
      - ./pgadmin_conf:/var/lib/pgadmin
      - ./servers.json:/servers.json:ro

volumes:
  postgis-data:
    name: ${POSTGIS_SERVER}-postgis-data
