CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20210324114559_InitalCreate') THEN
    CREATE EXTENSION IF NOT EXISTS postgis;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20210324114559_InitalCreate') THEN
    CREATE TABLE points (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        location geography (point) NOT NULL,
        CONSTRAINT pk_points PRIMARY KEY (id)
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20210324114559_InitalCreate') THEN
    INSERT INTO points (id, location)
    VALUES (1, GEOGRAPHY 'POINT (1 1)');
    INSERT INTO points (id, location)
    VALUES (2, GEOGRAPHY 'POINT (2 2)');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20210324114559_InitalCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('points', 'id'),
        GREATEST(
            (SELECT MAX(id) FROM points) + 1,
            nextval(pg_get_serial_sequence('points', 'id'))),
        false);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20210324114559_InitalCreate') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20210324114559_InitalCreate', '5.0.7');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20210427091951_Add3rdPresetPoint') THEN
    INSERT INTO points (id, location)
    VALUES (3, GEOGRAPHY 'POINT (3 3)');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20210427091951_Add3rdPresetPoint') THEN
    PERFORM setval(
        pg_get_serial_sequence('points', 'id'),
        GREATEST(
            (SELECT MAX(id) FROM points) + 1,
            nextval(pg_get_serial_sequence('points', 'id'))),
        false);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20210427091951_Add3rdPresetPoint') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20210427091951_Add3rdPresetPoint', '5.0.7');
    END IF;
END $$;
COMMIT;

