CREATE EXTENSION IF NOT EXISTS postgis;


CREATE TABLE points (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    location geography (point) NOT NULL,
    CONSTRAINT pk_points PRIMARY KEY (id)
);


INSERT INTO points (id, location)
VALUES (1, GEOGRAPHY 'POINT (1 1)');
INSERT INTO points (id, location)
VALUES (2, GEOGRAPHY 'POINT (2 2)');


SELECT setval(
    pg_get_serial_sequence('points', 'id'),
    GREATEST(
        (SELECT MAX(id) FROM points) + 1,
        nextval(pg_get_serial_sequence('points', 'id'))),
    false);


